version: '3.7'
services:
  mysql:
    build: ./db
    ports:
    - target: 3306
      published: 3306
      environment:
  service1:
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    build: ./service2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service3:
    build: ./service3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service4:
    build: ./service4
    - target: 5003
      published: 5003
      protocol: tcp

